import type { CompanyChildTable } from '../../shared/registration/registrationTypes';

export const companyChildTables: [CompanyChildTable, ...CompanyChildTable[]] = [
  {
    key: 'promotions',
    endpoint: 'promotions',
    label: 'PromoÃ§Ãµes',
    title: 'PromoÃ§Ãµes da empresa',
    columns: [
      { key: 'dsPromocao', label: 'PromoÃ§Ã£o' },
      { key: 'qtPeriodo', label: 'PerÃ­odo' },
      { key: 'vlDesconto', label: 'Desconto R$', type: 'money' },
      { key: 'pcDesconto', label: 'Desconto %' },
      { key: 'boInativo', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'dsPromocao', label: 'PromoÃ§Ã£o', type: 'text', required: true },
      { key: 'qtPeriodo', label: 'PerÃ­odo', type: 'number' },
      {
        key: 'idUnidadeTempo',
        label: 'Unidade de tempo',
        type: 'number',
        lookupEndpoint: 'time-units',
        lookupLabelKey: 'dsUnidadeTempo',
      },
      { key: 'vlDesconto', label: 'Desconto R$', type: 'number' },
      { key: 'pcDesconto', label: 'Desconto %', type: 'number' },
      { key: 'dtInicio', label: 'InÃ­cio', type: 'date' },
      { key: 'dtEncerramento', label: 'Encerramento', type: 'date' },
    ],
  },
  {
    key: 'studentPlans',
    endpoint: 'student-plans',
    label: 'Planos de Alunos',
    title: 'Planos de alunos da empresa',
    columns: [
      { key: 'idAluno', label: 'ID aluno' },
      { key: 'idPlano', label: 'ID plano' },
      { key: 'nrDiaPagamento', label: 'Dia pgto' },
      { key: 'dtAdmissao', label: 'AdmissÃ£o', type: 'date' },
      { key: 'boInativo', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'idAluno', label: 'Aluno', type: 'number', lookupEndpoint: 'students', lookupLabelKey: 'nmAluno' },
      { key: 'idPlano', label: 'Plano', type: 'number', lookupEndpoint: 'plans', lookupLabelKey: 'dsPlano' },
      {
        key: 'idPromocaoPlano',
        label: 'PromoÃ§Ã£o do plano',
        type: 'number',
        lookupEndpoint: 'promotion-plans',
        lookupLabelKey: 'id',
      },
      { key: 'nrDiaPagamento', label: 'Dia pagamento', type: 'number' },
      { key: 'dtAdmissao', label: 'AdmissÃ£o', type: 'date' },
    ],
  },
  {
    key: 'payments',
    endpoint: 'payments',
    label: 'Pagamentos',
    title: 'Pagamentos da empresa',
    columns: [
      { key: 'idAlunoPlano', label: 'ID aluno plano' },
      { key: 'vlPagamento', label: 'Valor', type: 'money' },
      { key: 'dtPagamento', label: 'Pagamento', type: 'date' },
      { key: 'boInativo', label: 'Status', type: 'status' },
    ],
    fields: [
      {
        key: 'idAlunoPlano',
        label: 'Aluno plano',
        type: 'number',
        lookupEndpoint: 'companies/{companyId}/children/student-plans',
        lookupLabelKey: 'id',
      },
      {
        key: 'idProdutoMovimentacao',
        label: 'MovimentaÃ§Ã£o',
        type: 'number',
        lookupEndpoint: 'companies/{companyId}/children/product-movements',
        lookupLabelKey: 'id',
      },
      { key: 'vlPagamento', label: 'Valor', type: 'number' },
      {
        key: 'idStatusPagamento',
        label: 'Status pagamento',
        type: 'number',
        lookupEndpoint: 'payment-statuses',
        lookupLabelKey: 'dsStatusPagamento',
      },
      {
        key: 'idFormaPagamento',
        label: 'Forma pagamento',
        type: 'number',
        lookupEndpoint: 'payment-methods',
        lookupLabelKey: 'dsFormaPagamento',
      },
      { key: 'dtPagamento', label: 'Data pagamento', type: 'date' },
    ],
  },
  {
    key: 'productMovements',
    endpoint: 'product-movements',
    label: 'MovimentaÃ§Ãµes de Produtos',
    title: 'MovimentaÃ§Ãµes de produtos',
    columns: [
      { key: 'idProduto', label: 'ID produto' },
      { key: 'idAluno', label: 'ID aluno' },
      { key: 'qtMovimentada', label: 'Qtd' },
      { key: 'vlUnitario', label: 'Valor', type: 'money' },
      { key: 'boInativo', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'idProduto', label: 'Produto', type: 'number', lookupEndpoint: 'products', lookupLabelKey: 'dsProduto' },
      { key: 'idAluno', label: 'Aluno', type: 'number', lookupEndpoint: 'students', lookupLabelKey: 'nmAluno' },
      { key: 'qtMovimentada', label: 'Qtd movimentada', type: 'number' },
      { key: 'vlUnitario', label: 'Valor unitÃ¡rio', type: 'number' },
      { key: 'qtDisponivel', label: 'Qtd disponÃ­vel', type: 'number' },
    ],
  },
  {
    key: 'companyFiles',
    endpoint: 'company-files',
    label: 'Arquivos da Empresa',
    title: 'Arquivos da empresa',
    columns: [
      { key: 'dsArquivo', label: 'Arquivo' },
      { key: 'idTiposArquivos', label: 'ID tipo' },
      { key: 'boInativo', label: 'Status', type: 'status' },
    ],
    fields: [
      {
        key: 'idTiposArquivos',
        label: 'Tipo de arquivo',
        type: 'number',
        lookupEndpoint: 'file-types',
        lookupLabelKey: 'dsTipo',
      },
    ],
  },
  {
    key: 'studentCheckIns',
    endpoint: 'student-check-ins',
    label: 'Aluno Check-ins',
    title: 'Check-ins de alunos',
    columns: [
      { key: 'idAlunoPlano', label: 'ID aluno plano' },
      { key: 'idPontos', label: 'ID pontos' },
      { key: 'dtCadastro', label: 'Cadastro', type: 'date' },
      { key: 'boInativo', label: 'Status', type: 'status' },
    ],
    fields: [
      {
        key: 'idAlunoPlano',
        label: 'Aluno plano',
        type: 'number',
        lookupEndpoint: 'companies/{companyId}/children/student-plans',
        lookupLabelKey: 'id',
      },
      {
        key: 'idAlunoTreinosSequencia',
        label: 'SequÃªncia do treino',
        type: 'number',
        lookupEndpoint: 'student-training-sequences',
        lookupLabelKey: 'nrOrdem',
      },
      { key: 'idPontos', label: 'Pontos', type: 'number', lookupEndpoint: 'points', lookupLabelKey: 'dsPontos' },
    ],
  },
  {
    key: 'themes',
    endpoint: 'themes',
    label: 'Tema',
    title: 'Temas',
    columns: [
      { key: 'dsTema', label: 'Tema' },
      { key: 'boInativo', label: 'Status', type: 'status' },
    ],
    fields: [{ key: 'dsTema', label: 'Tema', type: 'text', required: true }],
  },
];
